### ISSUE TITLE
Frequently used section

### ISSUE THREAD

**Issue by mlhsn** [arifszn/OneClick#38]
**Type**

Feature request

**What**

If there was a frequently used section in the display area, like we have on browser home screen It would have helped me reusing the buttons I use more frequently.

I can imagine 2 way to implement this:

1. We can rearrange more used button at the beginning for the arrangement, with some color change to the cards
2. We can have a separate section called **Frequently used** to where we sort out all those cards

**Comment by mrinmay7875** [comment]
I think this feature is already taken cared of as there is a bookmark button using which user can easily bookmark their frequently visited site.

<img width="374" alt="image" src="https://github.com/arifszn/OneClick/assets/33797909/b7e952ee-6af0-4d5e-8d23-960569c0585d">

**Comment by arifszn** [comment]
I agree.
